### PR TITLE
Feature: Item restoration service

### PR DESCRIPTION
**Pull request by Eronox**
## Goal
List characters recoverable items to later on choose to restore them.
This needs to be enabled in the AC plugin.

The finalized PR aims to close https://github.com/azerothcore/acore-cms/issues/77 

**Features**
* Part of ACP
* API supported

## Proposed changes

* Move page renderes to their own subfolder to make View files less bloated

## Code

**AC-CMS ADMIN**

- [x] Page in ACP
- [x] Setting to enable  + Make sure worldserver is confed for it (?)
- [x] Design
- [x] Show & select characters by account
- [x] Make call to the service
- [x] Handle statuses (200, 500, 404, etc)

**API Service**

- [x] Base service file/handler
- [x] SOAP: List restorable items by character GUID
- [x] SOAP: Restore item
- [x] Validation _(existing character, authorized to restore, etc)_
- [x] Error & status handling

### CODE REVIEW

**Comment by Eronox** [comment]
## Demo 

https://user-images.githubusercontent.com/20321723/145692325-28f28dbb-ecff-4508-a139-10cf5b22939f.mp4

**Comment by Eronox** [comment]
@Helias hopefully I've implemented this correctly so that it can be used for sites that only resources the API. 😄 

If not, please do let me know with some pointers!

**Comment by nicoaravena** [comment]
All looks really good, will do some testing tomorrow or monday.

**Comment by Helias** [comment]
Checking the video it seems that the user can use item restoration via the panel, that's ok, it's not an issue, but can he pay via woocommerce to get this service?
I was thinking to put the item-restoration in the Woocommerce Shop and let the user restores the item via shop.

**Comment by Eronox** [comment]
I missed the part around it being a buyable service, I suppose that's something we can add to the config when enabling the service: 

A) free to use
B) through shop

**Comment by Helias** [comment]
the config would be perfect, but in particular, making the item restoration free-to-use for specific users would be great

We could create a donator-user category and make for them the item-restoration free, for the rest, the users need to use the shop.

I don't know if it's feasible, but anyway, what you did so far is great, I hope we can adapt easily to use it via the shop, because that should be the main feature, making it for free via conf or for specific users is a plus.

**Comment by Helias** [comment]
p.s. = please solve merge conflicts

**Comment by Helias** [comment]
I could not edit your PR, so I made a PR to your branch to fix the merge conflicts and improve a bit the code quality reducing the redundant code https://github.com/Eronox/acore-cms/pull/1

if you can guys review it, specially @nicoaravena

**Comment by Eronox** [comment]
Merged it into the branch after reviewing it, also enabled :
> Allow edits by maintainers

I don't know about the pvprewards changes but the item restoration parts (basically, only the refactored way of init a page) looks great to me

**Comment by Helias** [comment]
I would say to merge this and start to work on a shop service to show on the e-commerce page

**Comment by nicoaravena** [comment]
I just tested it and works good, but I think there are some improvements to do to the UI. Like:
- The shadow of the item name it does not allow to read it well.
- Use wordpress button classes (e.g: `.button-primary`, because users can change the admin view colors and will look weird this kind of colors (bootstrap is good to use tables, containers and stuff like that, all related to color is better to leave it to wordpress).
- Character selector should be in the same level as the page title (next to that or at the right)
- When you restore all the items the table should disappear instead of just leave the table header.
- The Tools config view need an `<hr>` bellow the title.
image

Also the PvP Rewards view is broken after the merge, it can't load the `$data` and `$result` variables into the view.

Other than that is a pretty good job.

**Comment by Eronox** [comment]
**Updated design** 

* darker colors (same as menu backgrounds) to allow white items. (common) (this removes the shadow too)
* added null state
* placed character selection left-aligned per request
* use `button-primary` for buttons
* Add HR to tools config

image

**Comment by Eronox** [comment]
for the pvp rewards issue, I can't find the reason behind it in the merge diff 'nor reproduce local as i haven't really configured it up I suppose. 

image


I think this might be caused by the origin PR itself and not the merge conflict fix but I could be wrong

**Comment by nicoaravena** [comment]
All looks amazing.
About the pvp error, I did a rapid test and found that using the function extract in the `getPvpRewardsRender` does not work (the errors are Notice), so, this is my workaround for this problem:

```diff
diff --git a/srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/AdminPanel/SettingsView.php b/srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/AdminPanel/SettingsView.php
index bdb9515f..50256abf 100644
--- a/srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/AdminPanel/SettingsView.php
+++ b/srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/AdminPanel/SettingsView.php
@@ -29,17 +29,20 @@ class SettingsView {
     }
 
     public function getPvpRewardsRender($data, $result) {
-        return $this->loadPageLayout('PVPRewards');
+        return $this->loadPageLayout('PVPRewards', ['data' => $data, 'result' => $result]);
     }
 
     public function getToolsRender() {
         return $this->loadPageLayout('Tools');
     }
 
-    private function loadPageLayout($pageName) {
+    private function loadPageLayout($pageName, $varExtract=null) {
         wp_enqueue_style('bootstrap-css', '//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', array(), '5.1.3');
         wp_enqueue_style('acore-css', ACORE_URL_PLG . 'web/assets/css/main.css', array(), '0.1');
         wp_enqueue_script('bootstrap-js', '//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js', array(), '5.1.3');
+        if (is_array($varExtract) && count($varExtract) > 0) {
+            extract($varExtract);
+        }
         ob_start();
         include(__DIR__ . '/Pages/' . $pageName . '.php');
         return ob_get_clean();
```

With that working, i cant say is ready to merge

**Comment by Helias** [comment]
Thanks @Eronox , soon we will add it in production on chromiecraft!

**Pull request merged**
